export const categoryMapping: Record<string, string> = {
  Weapon: "Weapons",
  Construction: "Construction",
  Items: "#bp_deployables",
  Resources: "Resources",
  Attire: "Clothing",
  Tool: "Tools",
  Medical: "Medical",
  Food: "Food",
  Ammunition: "Ammo",
  Traps: "Traps",
  Misc: "Other",
  Component: "Components",
  Electrical: "Electrical",
  Fun: "Fun",
};
