version: 2
updates:
  - package-ecosystem: "bun" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      react:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react*"
      nextjs:
        patterns:
          - "next"
          - "@next/*"
          - "eslint-config-next"
      tanstack:
        patterns:
          - "@tanstack/*"
      embla-carousel:
        patterns:
          - "embla-carousel-*"
      upstash:
        patterns:
          - "@upstash/*"
      react-hook-form:
        patterns:
          - "react-hook-form"
          - "@hookform/*"
      drizzle:
        patterns:
          - "drizzle-orm"
          - "drizzle-kit"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "prettier-plugin-tailwindcss"
      mdx:
        patterns:
          - "@mdx-js/*"
          - "@types/mdx"
